### ISSUE TITLE
Finish create assessment

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#105]
Tarea: Terminar la tarea de crear assessment (ya iniciada)
Fecha optima entrega: 20/04/2016
Fecha de entrega final: 22/04/2016
Horas estimadas: 2 horas
Horas reales:
Incidencias:

**Comment by AlbertFX91** [comment]
Recuerda que la final estimamos 3.5
Horas gastadas: 3.5h (clavadas picha jaja flipante)
