### ISSUE TITLE
List all orders as brisboxer

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#108]
http://brisbox.herokuapp.com/list-all-orders

Tarea: Corregir listar todos los pedidos. Se queda cargando, nunca muestra el listado
Fecha optima entrega: 17/04/2016
Fecha de entrega final: 19/04/2016
Horas estimadas: 1 horas
Horas reales:
Incidencias:

**Comment by AlbertFX91** [comment]
The bug isn't reproducible in developer enviroment. Waiting to see if the save-order bugs the bd consistence

**Comment by rafaeldrs** [comment]
Corregido
