### ISSUE TITLE
List my assessment

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#110]
Tarea: Listar mis assessments (es una vista a parte del perfil, reutilizar la de list brisboxer's assessments. En mi perfil poner la URL a esta)
Fecha optima entrega: 24/04/2016
Fecha de entrega final: 26/04/2016
Horas estimadas: 2.5 horas
Horas reales:
Incidencias:

**Comment by AlbertFX91** [comment]
Horas usadas: 3h
