### ISSUE TITLE
Web video

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#148]

**Comment by AlbertFX91** [comment]
Elección de herramienta optima: 1.0 h
Grabaciones:
- Proceso de login, verificacion de correo y vista de perfil: 0.25 + 1h de montaje = 1.25 h
- Intro: 1h
- Accept brisboxer: 0.25 en total

**Comment by rafaeldrs** [comment]
Paso 1: Registro -> Correo verificar
Paso 2: Entrar como admin y desde el dashboard aceptarlo
Paso 3: Crear un order -> order checkout -> correo
Paso 4: Con el usuario creado, mostrar el listado y aceptar un par de pedidos
Paso 5: Mostrar el dashboard de un pedido
Paso 6: Mostrar perfil del brisboxer

160 Secs

**Comment by AlbertFX91** [comment]
Horas usadas: 5 - 6 h
