### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#7]
Login/Logout function must be developed just like explained in the weekly meeting

**Comment by AlbertFX91** [comment]
@rafaeldrs  Cambiado el estimado a 7 ya que es el tiempo que me ha llevado realizarlo debido a que he tenido que generar de nuevo las imágenes del equipo

**Comment by AlbertFX91** [comment]
[#4 Login.txt](https://github.com/victorjmarin/brisbox/files/169903/4.Login.txt)
