### ISSUE TITLE
List brisboxer's assessment

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#76]
Tarea: Listar los assessment de un brisboxer (el admin es el que puede acceder a esto desde el panel de control)
Fecha optima entrega: 22/04/2016
Fecha de entrega final: 24/04/2016
Horas estimadas: 2.5 horas
Horas reales:
Incidencias:

**Comment by AlbertFX91** [comment]
@rafaeldrs esto podríamos agruparlo en el list my assessments. De esta forma, al listar en el profile del brisboxer, matamos dos pajaros de un tiro

**Comment by AlbertFX91** [comment]
horas usadas: 0H debido a que reutilizaba una vista ya creada
