### ISSUE TITLE
Promotion code in order checkout

### ISSUE THREAD

**Issue by rafaeldrs** [victorjmarin/brisbox#98]
Tarea: En el order checkout un nuevo input por si tienes codigo de promoción. Hacer pruebas con "probrisbox".
Fecha optima entrega: 20/04/2016
Fecha de entrega final: 22/04/2016
Horas estimadas: 2 horas
Horas reales: **1.5 horas**
Incidencias: No existe ninguna incidencia como tal, pero como Stripe no cobra con menos de 5€ (al menos eso creo, porque he esperado una respuesta durante días que no he recibido por parte de Antonio), al introducir correctamente el código promocional, sigue con el envío del correo, no hace nada más. Yo le hubiese cobrado 1 céntimo para ver que en la cuenta tiene ALGO de dinero (para el futuro pago)

**Comment by cristianpoleyJS** [comment]
En progreso, esperando respuesta de Antonio.
